type User {
    name: String! @unique
    ticket: Ticket @relation
}

type Ticket {
    owner: User!
    row1: [String!]!
    row2: [String!]!
    row3: [String!]!
}

type Query {
    allTickets: [Ticket]
    findUserByName(name: String!): User
}



